def test_fail():
    # asserts can also contain error message, that will be displayed in
    # test results in case of the failure
    assert 1 == 2, "one is not equal to two"
